# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
script = "script"
solc = "0.8.26"
src = "contracts"
test = "test"
libs = ["dependencies"]
auto_detect_remappings = true

[dependencies]
forge-std = { version = "1.9.1" }
"@openzeppelin-contracts" = { version = "5.0.2" }
"@openzeppelin-contracts-upgradeable" = { version = "5.0.2" }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
bnb = "${BNB_RPC_URL}"
bnb_testnet = "${BNB_TESTNET_RPC_URL}"