/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProductFactory } from "./ProductFactory";
export * as factories from "./factories";
export { ProductFactory__factory } from "./factories/ProductFactory__factory";
